name: competition_bridge

topics:
  hv_pose:
    topic: /HV_\d+
    type: geometry_msgs/msg/PoseStamped
    from_domain: 100
    to_domain: 1
    regex: true

  ego_pose:
    topic: /CAV_01
    type: geometry_msgs/msg/PoseStamped
    from_domain: 100
    to_domain: 1
    remap: /Ego_pose
