/**:
  ros__parameters:
    cav_ids: [24, 5, 6, 9]
    high_priority_ids: [24, 5]
    target_cav_id: 24

    mpc_settings:
      Q_pos: 95.4
      Q_heading: 85.6
      R_v: 0.5
      R_w: 0.6
      max_velocity: 1.2
      max_accel: 1.5
      max_angular_vel: 2.8
      horizon: 160

hv_settings:
  - id: 19
    node_sequence: [38, 41, 62, 38]
  - id: 20
    node_sequence: [38, 41, 62, 38]